# Specify what the robot base is and what the world base is
world_base: odom
robot_base: body

num_cameras: 1
update_policy: fifo
# Configurable section
cameras_registered:
  realsense:
    image_rectified: /zed2i/zed_node/rgb/image_rect_color
    depth_registered: /zed2i/zed_node/depth/depth_registered
    camera_info: /zed2i/zed_node/rgb/camera_info
    # By not specifying these, we lookup the transform frame instead. (They do no need to be specified)
    pose_with_covariance: ''
    pose: ''


# Define intermediate joints needed, but id them with
# child link to keep uniqueness.
# joints: # husky joints are already in the urdf
  # Angle for the new bracket
  # camera_link:
  #   parent: front_rail
  #   translation:
  #     x: 0.264764
  #     y: 0.0175
  #     z: 0.036
  #   rotation:
  #     x: 0
  #     y: 0.258819
  #     z: 0
  #     w: 0.9659258
